export const DUMMY_WORDS = [
  {
    id: 1,
    name: 'Serendipity',
    slug: 'serendipity',
    term: 'Serendipity',
    type: 'noun',
    order: 1,
    total: 3213,
    category: { name: 'Literature' },
    definition: 'the occurrence and development of events by chance in a happy or beneficial way.',
    sentence: 'A fortunate stroke of serendipity led him to the discovery of the lost treasure.',
    image: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 2,
    name: 'Ephemeral',
    slug: 'ephemeral',
    term: 'Ephemeral',
    type: 'adjective',
    order: 2,
    total: 3213,
    category: { name: 'Nature' },
    definition: 'lasting for a very short time.',
    sentence: 'The beauty of the sunset was ephemeral, fading into darkness within minutes.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 3,
    name: 'Luminous',
    slug: 'luminous',
    term: 'Luminous',
    type: 'adjective',
    order: 3,
    total: 3213,
    category: { name: 'Science' },
    definition: 'full of or shedding light; bright or shining, especially in the dark.',
    sentence: 'The moon cast a luminous glow over the silent, snowy landscape.',
    image: 'https://images.unsplash.com/photo-1444703686981-a3abb99d4fe3?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 4,
    name: 'Ethereal',
    slug: 'ethereal',
    term: 'Ethereal',
    type: 'adjective',
    order: 4,
    total: 3213,
    category: { name: 'Art' },
    definition: 'extremely delicate and light in a way that seems too perfect for this world.',
    sentence: 'The singer had an ethereal voice that felt like it came from another realm.',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 5,
    name: 'Mellifluous',
    slug: 'mellifluous',
    term: 'Mellifluous',
    type: 'adjective',
    order: 5,
    total: 3213,
    category: { name: 'Music' },
    definition: '(of a voice or words) sweet or musical; pleasant to hear.',
    sentence: 'The orchestra played a mellifluous melody that calmed the restless crowd.',
    image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 6,
    name: 'Petrichor',
    slug: 'petrichor',
    term: 'Petrichor',
    type: 'noun',
    order: 6,
    total: 3213,
    category: { name: 'Nature' },
    definition: 'a pleasant smell that frequently accompanies the first rain after a long period of warm, dry weather.',
    sentence: 'The earthy scent of petrichor filled the air as the first raindrops hit the pavement.',
    image: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 7,
    name: 'Sempiternal',
    slug: 'sempiternal',
    term: 'Sempiternal',
    type: 'adjective',
    order: 7,
    total: 3213,
    category: { name: 'Time' },
    definition: 'eternal and unchanging; everlasting.',
    sentence: 'The stars seem to have a sempiternal presence in the vast night sky.',
    image: 'https://images.unsplash.com/photo-1506318137071-a8e063b4b451?q=80&w=500&auto=format&fit=crop',
  },
  {
    id: 8,
    name: 'Quintessential',
    slug: 'quintessential',
    term: 'Quintessential',
    type: 'adjective',
    order: 8,
    total: 3213,
    category: { name: 'Philosophy' },
    definition: 'representing the most perfect or typical example of a quality or class.',
    sentence: 'The white picket fence is often seen as the quintessential symbol of suburban life.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=500&auto=format&fit=crop',
  },
];
